import {
  LayoutGrid,
  Briefcase,
  TrendingUp,
  Landmark,
  Shirt,
  CreditCard,
  ArrowLeftRight,
  BarChart3,
  FileText,
  SlidersHorizontal,
  Search,
  Bell,
  Calendar,
  RefreshCw,
  Sun,
  Moon,
  Menu,
  X,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowUp,
  ArrowDown,
  Wallet,
  Sparkles,
  AlertTriangle,
  Clock,
  Check,
  MoreVertical,
  ShoppingCart,
  Eye,
  EyeOff,
  Trash2,
  Inbox,
  Plus,
  Download,
  Pencil,
  LogOut,
  type LucideIcon,
} from 'lucide-react'

export const icons = {
  dashboard: LayoutGrid,
  portfolio: Briefcase,
  stocks: TrendingUp,
  banks: Landmark,
  pfepf: Shirt,
  cards: CreditCard,
  transactions: ArrowLeftRight,
  analytics: BarChart3,
  reports: FileText,
  settings: SlidersHorizontal,
  search: Search,
  bell: Bell,
  calendar: Calendar,
  refresh: RefreshCw,
  sun: Sun,
  moon: Moon,
  menu: Menu,
  close: X,
  collapse: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  up: ArrowUp,
  down: ArrowDown,
  netWorth: Wallet,
  ai: Sparkles,
  warning: AlertTriangle,
  due: Clock,
  paid: Check,
  more: MoreVertical,
  buy: ShoppingCart,
  alert: Bell,
  view: Eye,
  viewOff: EyeOff,
  remove: Trash2,
  empty: Inbox,
  add: Plus,
  download: Download,
  edit: Pencil,
  logout: LogOut,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof icons

export function Icon({
  name,
  className = 'h-4 w-4',
  strokeWidth = 2,
}: {
  name: IconName
  className?: string
  strokeWidth?: number
}) {
  const Cmp = icons[name]
  return <Cmp className={className} strokeWidth={strokeWidth} />
}
